# Path to your oh-my-zsh installation.
export ZSH=/home/jakob/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(gitfast)

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

export WORKON_HOME=$HOME/.virtualenv
export PROJECT_HOME=$HOME/code
source $HOME/.local/bin/virtualenvwrapper.sh

export PATH=$PATH:$HOME/.vimpkg/bin

alias vim="stty stop '' -ixoff ; vim"
# `Frozing' tty, so after any command terminal settings will be restored
ttyctl -f
# Remap CAPS LOCK to ESCAPE
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

source $ZSH/oh-my-zsh.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/jakob/google-cloud-sdk/path.zsh.inc' ]; then source '/home/jakob/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/jakob/google-cloud-sdk/completion.zsh.inc' ]; then source '/home/jakob/google-cloud-sdk/completion.zsh.inc'; fi

export DOCKER_GATEWAY="$(ifconfig | grep docker0 -A1 | tail -1 | sed 's#.*inet \([0-9.]*\).*#\1#')"
export RETHINKDB_TEST_ENDPOINT=$DOCKER_GATEWAY:28015
export REINFER_TEST_NAMESPACE='python'
export LDAP_TEST_ENDPOINT=$DOCKER_GATEWAY:8389
export ELASTICSEARCH_TEST_ENDPOINT=$DOCKER_GATEWAY:9200
export DEFAULT_MODEL_FAMILY="english"
export LABELLER_MODEL_ID="random"
export THEME_MODEL_ID="random"

function jenkins () {
    local port1=${1:-39101}
    local port2=${2:-39102}
    sh -c "sleep 2 && xdg-open http://localhost:${port1}" &
    gcloud compute ssh --project=reinfer-ci --zone=europe-west1-c jenkins -- -L ${port1}:localhost:8080 -L ${port2}:localhost:8971
}

function staging-rethink () {
    local port=${1:-38016}
    gcloud compute ssh --project=reinfer-staging --zone=europe-west1-c rethink-1 -- -L ${port}:rethink-1:28015 -L 30048:rethink-1:8080
}

function prod-rethink () {
    local port=${1:-48016}
    gcloud compute ssh --project=reinfer-prod --zone=europe-west1-d rethink-7k30 -- -L ${port}:rethink-7k30:28015 -L 40048:rethink-7k30:8080
}

function staging-elastic () {
    local port=${1:-39201}
    gcloud compute ssh --project=reinfer-staging --zone=europe-west1-c elasticsearch-1 -- -L ${port}:elasticsearch-1:9200
}

alias pt='papertrail'
alias ptp='papertrail -g prod'
alias pts='papertrail -g staging'
alias gu=gsutil
alias dcr='docker-compose rm'
alias dcu='docker-compose up'
alias dcs='docker-compose stop'
alias dcb='docker-compose build'

function ptsf () {
  papertrail -g staging -f gcp-staging-$1
}

function ptpf () {
  papertrail -g prod -f gcp-prod-$1
}

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# The following lines were added by jakob
zstyle ':completion:*' insert-tab false
# End of lines added by jakob
# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored
zstyle :compinstall filename '/home/jakob/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=100000
unsetopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install
